const SET_MENU_SELECTED = "SET_MENU_SELECTED";
const SET_LEAGUE_GAME_SELECTED = "SET_LEAGUE_GAME_SELECTED";
const SET_LEAGUE_SELECTED = "SET_LEAGUE_SELECTED";
const SET_SUBMENU_SELECTED = "SET_SUBMENU_SELECTED";
const SET_SUBMENU_COMPARISON_SELECTED = "SET_SUBMENU_COMPARISON_SELECTED";
const SET_TOTAL_FIELD_SELECTED = "SET_TOTAL_FIELD_SELECTED";
const SET_WINDOW_FIELD_SELECTED = "SET_WINDOW_FIELD_SELECTED";
const SET_DEFAULT_SELECTED = "SET_DEFAULT_SELECTED";
const IS_COMPARISON = "IS_COMPARISON";
const IS_DATA = "IS_DATA";
const IS_AGGREGATION = "IS_AGGREGATION";
const IS_CROSS = "IS_CROSS";
const SET_BOOL_STATUS = "SET_BOOL_STATUS";
const MENU_SELECTED_IS_LOADED = "MENU_SELECTED_IS_LOADED";

const CATEGORY_NAME = "CATEGORY_NAME";
const CATEGORY_NAME_COMPARISON = "CATEGORY_NAME_COMPARISON";

export {
	SET_MENU_SELECTED,
	SET_LEAGUE_GAME_SELECTED,
	SET_LEAGUE_SELECTED,
	SET_SUBMENU_SELECTED,
	SET_SUBMENU_COMPARISON_SELECTED,
	SET_TOTAL_FIELD_SELECTED,
	SET_WINDOW_FIELD_SELECTED,
	SET_DEFAULT_SELECTED,
	IS_COMPARISON,
	IS_DATA,
	IS_AGGREGATION,
	IS_CROSS,
	SET_BOOL_STATUS,
	MENU_SELECTED_IS_LOADED,
	CATEGORY_NAME,
	CATEGORY_NAME_COMPARISON,
};
