// MENU
const SET_DEFAULT_MENU = "SET_DEFAULT_MENU";
const UPDATE_LEAGUE_GAMES = "SET_LEAGUE_GAMES";
const SET_DEFAULT_MENU_FIELDS = "SET_DEFAULT_MENU_FIELDS";
const CHANGE_DEFAULT_THEME = "CHANGE_DEFAULT_THEME";

export {
	SET_DEFAULT_MENU,
	UPDATE_LEAGUE_GAMES,
	SET_DEFAULT_MENU_FIELDS,
	CHANGE_DEFAULT_THEME,
};
