// MENU
const SET_DEFAULT_MENU = "SET_DEFAULT_MENU";
const UPDATE_LEAGUE_GAMES = "SET_LEAGUE_GAMES";
const SET_DEFAULT_MENU_FIELDS = "SET_DEFAULT_MENU_FIELDS";
const CHANGE_DEFAULT_THEME_STR = "CHANGE_DEFAULT_THEME_STR";
const CHANGE_DEFAULT_THEME_BOOL = "CHANGE_DEFAULT_THEME_BOOL";
const CHANGE_TABLE_VERTICAL = "CHANGE_TABLE_VERTICAL";

export {
	SET_DEFAULT_MENU,
	UPDATE_LEAGUE_GAMES,
	SET_DEFAULT_MENU_FIELDS,
	CHANGE_DEFAULT_THEME_STR,
	CHANGE_DEFAULT_THEME_BOOL,
	CHANGE_TABLE_VERTICAL,
};
