// SETTINGS
// AGGREGATION
const UPDATE_AGGREGATION_TYPE = "UPDATE_AGGREGATION_TYPE";
const UPDATE_AGGREGATION_COMPARISON = "UPDATE_AGGREGATION_COMPARISON";
// cross comparison
const UPDATE_CCOMP_POSITION = "UPDATE_CCOMP_POSITION";
const UPDATE_CCOMP_TYPE = "UPDATE_CCOMP_TYPE";
const UPDATE_CCOMP_TOTAL_FIELD = "UPDATE_CCOMP_TOTAL_FIELD";
const UPDATE_CCOMP_WINDOW_FIELD = "UPDATE_CCOMP_WINDOW_FIELD";
// comparison
const UPDATE_COMPARISON = "UPDATE_COMPARISON";
const UPDATE_FLAT = "UPDATE_FLAT";
const UPDATE_GAME_STAGE = "UPDATE_GAME_STAGE";

export {
	UPDATE_AGGREGATION_TYPE,
	UPDATE_AGGREGATION_COMPARISON,
	UPDATE_CCOMP_POSITION,
	UPDATE_CCOMP_TYPE,
	UPDATE_CCOMP_TOTAL_FIELD,
	UPDATE_CCOMP_WINDOW_FIELD,
	UPDATE_COMPARISON,
	UPDATE_FLAT,
	UPDATE_GAME_STAGE,
};
